"""Builds Refractory's icon font: a subset of Lucide (https://lucide.dev, ISC licence) with only the
icons the interface uses, and src/ui/Icons.h with their code points.

    python tools/lucide_icons.py <lucide-static package folder>

The package is the npm tarball https://registry.npmjs.org/lucide-static/-/lucide-static-<version>.tgz,
extracted. Needs fontTools (pip install fonttools). To add an icon, add it to ICONS and rerun; the
outputs are checked in so the build needs neither the package nor Python.
"""
import json
import pathlib
import sys

from fontTools import subset

VERSION = "1.52.0"

# (constant, Lucide name). Constants become ICON_<NAME> in Icons.h.
ICONS = [
    ("ALERT", "circle-alert"),
    ("APERTURE", "aperture"),
    ("ARROW_LEFT", "arrow-left"),
    ("ARROW_RIGHT", "arrow-right"),
    ("ARROW_UP", "arrow-up"),
    ("BOOK", "book-open"),
    ("BRUSH", "brush"),
    ("CAMERA", "camera"),
    ("CHART", "chart-column"),
    ("CHECK", "check"),
    ("CHEVRON_DOWN", "chevron-down"),
    ("CHEVRON_LEFT", "chevron-left"),
    ("CHEVRON_RIGHT", "chevron-right"),
    ("CHEVRON_UP", "chevron-up"),
    ("CIRCLE", "circle"),
    ("CLIPPING", "triangle-alert"),
    ("COLUMNS", "columns-2"),
    ("CONTRAST", "contrast"),
    ("COPY", "copy"),
    ("CPU", "cpu"),
    ("CROP", "crop"),
    ("DOWNLOAD", "download"),
    ("DROPLET", "droplet"),
    ("ELLIPSIS", "ellipsis"),
    ("EXPORT", "upload"),
    ("EXTERNAL", "external-link"),
    ("EYE", "eye"),
    ("EYE_OFF", "eye-off"),
    ("FILE_PLUS", "file-plus"),
    ("FILTER", "funnel"),
    ("FIT", "scan"),
    ("FLAG", "flag"),
    ("FLAG_OFF", "flag-off"),
    ("FLIP", "flip-horizontal-2"),
    ("FOLDER", "folder"),
    ("FOLDER_OPEN", "folder-open"),
    ("FRAME", "frame"),
    ("GAMUT", "triangle"),
    ("GRID", "layout-grid"),
    ("GRID_SMALL", "grid-3x3"),
    ("HAND", "hand"),
    ("HELP", "circle-help"),
    ("HISTORY", "history"),
    ("HOME", "house"),
    ("IMAGE", "image"),
    ("IMAGES", "images"),
    ("INFO", "info"),
    ("KEYBOARD", "keyboard"),
    ("LAYERS", "layers"),
    ("LINK", "link"),
    ("LIST", "list"),
    ("LOADER", "loader-circle"),
    ("LOCK", "lock"),
    ("LOUPE", "square"),
    ("MAP", "map"),
    ("MASK", "square-dashed"),
    ("MAXIMIZE", "maximize"),
    ("MINIMIZE", "minimize"),
    ("MINUS", "minus"),
    ("MONITOR", "monitor"),
    ("MOVE", "move"),
    ("PALETTE", "palette"),
    ("PASTE", "clipboard-paste"),
    ("PAUSE", "pause"),
    ("PIN", "pin"),
    ("PIPETTE", "pipette"),
    ("PLAY", "play"),
    ("PLUS", "plus"),
    ("REDO", "redo-2"),
    ("REFRESH", "refresh-cw"),
    ("RESET", "rotate-ccw"),
    ("ROTATE", "rotate-cw"),
    ("SAVE", "save"),
    ("SEARCH", "search"),
    ("SETTINGS", "settings"),
    ("SLIDERS", "sliders-horizontal"),
    ("SORT", "arrow-up-down"),
    ("SPARKLES", "sparkles"),
    ("SPLIT", "square-split-horizontal"),
    ("STAR", "star"),
    ("SUN", "sun"),
    ("SURVEY", "layout-dashboard"),
    ("TAG", "tag"),
    ("TRASH", "trash-2"),
    ("UNDO", "undo-2"),
    ("UNLINK", "unlink"),
    ("UNLOCK", "lock-open"),
    ("WAND", "wand-sparkles"),
    ("WORKFLOW", "workflow"),
    ("X", "x"),
    ("ZOOM_IN", "zoom-in"),
    ("ZOOM_OUT", "zoom-out"),
]


def main():
    pkg = pathlib.Path(sys.argv[1])
    root = pathlib.Path(__file__).resolve().parent.parent
    codes = json.loads((pkg / "font" / "codepoints.json").read_text())
    missing = [n for _, n in ICONS if n not in codes]
    if missing:
        sys.exit("not in Lucide %s: %s" % (VERSION, ", ".join(missing)))
    points = sorted(codes[n] for _, n in ICONS)

    out_dir = root / "third_party" / "lucide"
    out_dir.mkdir(parents=True, exist_ok=True)
    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ["*"]
    options.notdef_outline = True
    font = subset.load_font(str(pkg / "font" / "lucide.ttf"), options)
    sub = subset.Subsetter(options)
    sub.populate(unicodes=points)
    sub.subset(font)
    subset.save_font(font, str(out_dir / "lucide-refractory.ttf"), options)
    (out_dir / "LICENSE").write_text((pkg / "LICENSE").read_text())

    lines = [
        "#pragma once",
        "// Generated by tools/lucide_icons.py from Lucide %s (ISC licence). Do not edit." % VERSION,
        "// Icons are merged into the UI font (Private Use Area code points), so they go in any label:",
        '// ImGui::Button(ICON_EXPORT " Export").',
        "",
    ]
    for name, lucide in sorted(ICONS):
        cp = codes[lucide]
        utf8 = chr(cp).encode("utf-8")
        lines.append('#define ICON_%-14s "%s"  // %s' % (name, "".join("\\x%02x" % b for b in utf8), lucide))
    lines += [
        "",
        "// Code point range covering every icon, for the font atlas.",
        "#define ICON_MIN 0x%04x" % points[0],
        "#define ICON_MAX 0x%04x" % points[-1],
        "",
    ]
    (root / "src" / "ui" / "Icons.h").write_text("\n".join(lines), newline="\n")
    print("%d icons, %d bytes" % (len(ICONS), (out_dir / "lucide-refractory.ttf").stat().st_size))


if __name__ == "__main__":
    main()
